### ISSUE TITLE
Adobe-wide pypi deployment credentials

### ISSUE THREAD

**Issue by filmaj** [adobe/NLP-Cube#103]
Hi, I'm Fil from Adobe's Open Source Office.

FYI I recently created an adobe-wide pypi account: https://pypi.org/user/adobe/

If you have access  to adobe's corporate network, you can see more info about plans for centralizing adobe releases to pypi here: https://git.corp.adobe.com/OpenSourceAdvisoryBoard/handbook/issues/21

If you'd like to try publishing this project under the adobe account, let me know / take a look at the URL above.

**Comment by tiberiu44** [comment]
Hi @filmaj,
Nlp-Cube appears under the adobe user (by adding the user as an owner of the project). Should we close this?

**Comment by filmaj** [comment]
Yes, absolutely!
