### ISSUE TITLE
Does cube support enhanced/collapsed dependency parsing.

### ISSUE THREAD

**Issue by shepherd1530** [adobe/NLP-Cube#116]
Currently our service is based on the java based Stanford's core NLP library and we are looking to migrate from java to python in our backend systems. Does cube provide enhance dependency annotations and if yes how will one go about getting them? Thanks

**Comment by tiberiu44** [comment]
If I understand correctly from the UD annotation guidelines, we would have to add null-nodes to the sentence. We don't support this at the moment and we haven't begun discussing this enhancement.

Sorry to disappoint :(

**Comment by shepherd1530** [comment]
Alright, Thanks.
