### ISSUE TITLE
The future of the Cube project?

### ISSUE THREAD

**Issue by mprinc** [adobe/NLP-Cube#118]
I see that the latest contribution on the project was over 11 months ago. What is the status and the future of the Cube Project?

Is there any stable use case for it under the Adobe umbrella or it was an side-experiment?

Thanks

**Comment by tiberiu44** [comment]
Hi @mprinc ,

I think you are refering to the last contribution on the main branch. However, you can checkout the 2.0 branch. The last contribution is on 5th of May 2020. 

Pretraining models is also part of the NLP-Cube development cycle and it is not reflected in the Git contributions. We are trying to release the new version+models for some time now, but this takes time.

So, in short, NLP-Cube is actively developed and supported.

Best,
Tibi

**Comment by mprinc** [comment]
Thank you @tiberiu44 !
Looking forward the future work.

Would be great to have some roadmap or upcoming features, etc
