### ISSUE TITLE
Additional language models needed

### ISSUE THREAD

**Issue by Spaskich** [adobe/NLP-Cube#132]
**Is your feature request related to a problem? Please describe.**
I've been using the previous version of NLP-Cube for a wide array of languages, most of which are not present in 3.0. 

**Describe the solution you'd like**
Updated language models for Czech, Finnish, Greek, Hindi, Indonesian, Portuguese, Russian, Slovak, Slovenian, Swedish, and Turkish.

**Describe alternatives you've considered**
Can the NLP-Cube 3.0 version work with the older v1.1 models? If so, do you plan on dropping support for them in the future?

**Comment by tiberiu44** [comment]
Indonesian is finished and uploaded.

**Comment by Spaskich** [comment]
I tested them by modifying and running the whole project.

**Comment by Spaskich** [comment]
Okay, it's probably something on my end then, I'll look into it. Thanks for the help and the quick response with the models!

**Comment by Spaskich** [comment]
Great! Thanks a lot for the help!
