### ISSUE TITLE
pip-ify NLP-Cube

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/NLP-Cube#17]
In the near future we should be able to install this as a python package like "pip install nlpcube". This is a major issue as it will also involve having ready the python API for all tasks.

## Expected Result

Initial results: 
1. Install by "pip install"
2. Import it like "import nlpcube as cube"

Later results - decide on the usage API:
3. Agree on a way to use it, be it in a static manner (e.g. "cube.load(<model>)" , "cube.tokenize(<a string>", etc. like NLTK) or object-centered (e.g. instantiate a cube object, set a pipeline from the start and then just call the wrapper function OR let the user call individual functions of the object (sentencesplit/tok/tag/etc.) sequentially).

**Comment by tiberiu44** [comment]
Solved pip3 install nlpcube.

Full example: https://github.com/adobe/NLP-Cube/blob/master/examples/simple_example.ipynb
