### ISSUE TITLE
Add notebook(s) for tokenization 

### ISSUE THREAD

**Issue by ruxandraburtica** [adobe/NLP-Cube#47]
**Is your feature request related to a problem? Please describe.**
It's related to the adoption of NLP-cube

**Describe the solution you'd like**
A Jupyter notebook example that emphasizes how tokenization can be done.

**Comment by tiberiu44** [comment]
We added a full usage example here: https://github.com/adobe/NLP-Cube/blob/master/examples/simple_example.ipynb
