### ISSUE TITLE
Add a list of supported languages

### ISSUE THREAD

**Issue by tiberiu44** [adobe/NLP-Cube#69]
**Is your feature request related to a problem? Please describe.**
There is no way of telling if NLP-Cube supports or not a certain language. Also, custom corpora introduces some suffixes which are hard to guess.

**Describe the solution you'd like**
Either update the documentation or add a function to list or languages that are uploaded in the repo. I would prefer the later.

**Comment by dumitrescustefan** [comment]
Documentation should be clear about which languages are supported. Also, the ModelStore object has a function named list_online_models() that lets the user see what models are online in the format language_code - version. 

After we finish the documentation we should have a listing as well as a correspondence between languages and language codes.

**Comment by tiberiu44** [comment]
The list can be obtained by consulting [Universal Dependencies](http://universaldependencies.org/)
