### ISSUE TITLE
Rebuild and document the REST API

### ISSUE THREAD

**Issue by ruxandraburtica** [adobe/NLP-Cube#7]
## Need

Document the REST API.

## Deliverables

Upgrade our current API, and build a REST version.
Note that we should use HATEOAS from the start-off (maybe use [marshmallow](https://flask-marshmallow.readthedocs.io/en/latest/)?)

**Comment by tiberiu44** [comment]
https://github.com/adobe/NLP-Cube/blob/master/examples/simple_example.ipynb
