### ISSUE TITLE
Python package nlpcube needs update

### ISSUE THREAD

**Issue by edubey** [adobe/NLP-Cube#76]
Summary of the issue.

I was exploring the package from pip **https://pypi.org/project/nlpcube/0.1.0.1/**
but struggled with version with using version no like below
`from cube.api import Cube
cube=Cube(verbose=True)
cube.load("en", "1.0")`

but later found it has been fixed in this [commit ](https://github.com/adobe/NLP-Cube/commit/4c9dba132153ed1d199924446bf170c8725a76e8#diff-0c697c29293f284725722d54a2c6a868R158)

## Expected Result
It should try to  download the package with the given version
Since fix is there in master branch, Are we planning to do a new release of [PYPI](https://pypi.org/project/nlpcube/0.1.0.1/) package ?

## Actual Result

Error Message `TypeError: join() argument must be str or bytes, not 'float'`

## Reproduction Steps

Please provide the commands list that help others reproduce the same issue you're experiencing. 
1. Install using *pip3 install nlpcube*
2. Run the following lines of code

`from cube.api import Cube
cube=Cube(verbose=True)
cube.load("en", "1.2")`

## System Information

Please provide some basic information about your system:
* GPU support (enabled/disabled)
* Hyperparameters used
* Training set used (embeddings, language, ud-version)
* Dynet version
* Python version
* Operating system

**Comment by tiberiu44** [comment]
Hi @edubey ,

Thank you for letting us know. I will check if any of the updates (since 8 October 2018) break compatibility with the pre-trained models. If not, we will release a new pip package for NLP-Cube. Otherwise, things will get a little complicated because training takes a lot of time. Anyway, I will keep you updated.

Best,
Tibi

**Comment by tiberiu44** [comment]
Adding, @dumitrescustefan to this list. The commit did not fix the issue:
```python
cube.load('en', version='1.1')
```
generates
```python
~/Projects/test/venv/lib/python3.7/site-packages/cube/io_utils/model_store.py in find(self, lang_code, version, verbose)
    161                 cloud_version = self._version_to_download(lang_code, version=version)
    162                 if cloud_version == None:
--> 163                     raise Exception("Version ["+str(version)+"] for language ["+lang_code+"] was not found in the online repository. Maybe try using .find(version='latest') to auto-download the latest model?")
    164                 self._download_model(lang_code, str(cloud_version))
    165                 return os.path.join(self.disk_path,lang_code+"-"+str(cloud_version)) #self._load(lang_code,version)

Exception: Version [1.1] for language [en] was not found in the online repository. Maybe try using .find(version='latest') to auto-download the latest model?
```

Same goes for version 1.0

**Comment by tiberiu44** [comment]
I have just tested the latest NLP-Cube package and it works as expected. Thank you @dumitrescustefan . I will close this issue.

**Comment by edubey** [comment]
Thanks @dumitrescustefan @tiberiu44
