### ISSUE TITLE
Model Performance

### ISSUE THREAD

**Issue by theotheo** [adobe/NLP-Cube#81]
Hi there! 

Is there any model performance table like [this](http://ufal.mff.cuni.cz/udpipe/models#universal_dependencies_23_models_performance)?

**Comment by tiberiu44** [comment]
Hi @theotheo ,

We have the same table in the [system description paper](http://www.aclweb.org/anthology/K18-2017) on page 7.

**Comment by dumitrescustefan** [comment]
Actually, I've been putting off merging a script that generates tables like that. I'll try to put everything online in a couple of days. We should have the table in the .md format. Also, accuracy figures should improve compared to the original system description paper, especially for lemmas. 

Furthermore, all the tests are now on model versions 1.0. We'll release in some time models 1.1 which are smaller and for some languages have better performance.

I'll come back with the link to the results here.

**Comment by dumitrescustefan** [comment]
Hi @theotheo 

I have added the initial performance table in the main readme. After we finish with the 1.1 models i'll move the table into a separate readme with more details. I did not include all the metrics as they are kind of technical. If you need all the details I can forward you the json which is the source for this table.

**Comment by tiberiu44** [comment]
I'm going to close this issue
