### ISSUE TITLE
cube.load cannot download wiki.{}.vec

### ISSUE THREAD

**Issue by KoichiYasuoka** [adobe/NLP-Cube#91]
**Describe the bug**
Cannot load wiki.{}.vec

**To Reproduce**
1. remove all models in ~/.nlpcube
2. cube.load("en") as described in https://github.com/adobe/NLP-Cube

**Possible Reason**
Facebook's wiki.en.vec was moved to https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.en.vec but your "metadata.json" points to old place. So as other wiki.{}.vec

**Comment by dumitrescustefan** [comment]
Hi! Thanks for letting us know, I'll update the models accordingly. 
I'll let you know as soon as the operation finishes.

**Comment by dumitrescustefan** [comment]
@KoichiYasuoka we've re-uploaded all the models with the corrected metadata. Everything should work as expected. Also, we're very close to releasing models v1.1 which no longer require embeddings. We'll update the main readme with performance testing to compare v1.0 with v1.1.

Thanks again for the notification!

**Comment by KoichiYasuoka** [comment]
Thanks! I've just confirmed they work well. I'm looking forward to your models v1.1.

**Comment by tiberiu44** [comment]
Hi @KoichiYasuoka ,

I'm using this issue to get in touch with you with a short question. 

Do you know of any Japanese corpus for tokenization? We are working on another set of models and a major change in the code as well, but it seems the UD is still insufficient to accurately train out tokenizer.

Best,
Tibi

**Comment by KoichiYasuoka** [comment]
The Balanced Corpus of Contemporary Written Japanese (BCCWJ) https://pj.ninjal.ac.jp/corpus_center/bccwj/en/ is widely used in Japan. On the other hand we often choose "dictionary-based approach" for tokenization & POS-tagging of Japanese texts, such as mecab-ipadic-NEologd https://github.com/neologd/mecab-ipadic-neologd .
