### ISSUE TITLE
ConllEntry should have a __repr__ function

### ISSUE THREAD

**Issue by dumitrescustefan** [adobe/NLP-Cube#93]
Right now, output looks like: 
>>> text="This is the text I want segmented, tokenized, lemmatized and annotated with POS and dependencies."
>>> sentences=cube(text)
>>> print(sentences)
[[<cube.io_utils.conll.ConllEntry object at 0x7f5ae924b358>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252080>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae92520f0>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252160>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae92521d0>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252240>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae92522b0>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252320>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252390>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252400>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252470>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae92524e0>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252550>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae92525c0>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252630>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae92526a0>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252710>, <cube.io_utils.conll.ConllEntry object at 0x7f5ae9252780>]]
 
when we print a sentence object. We should have a __repr__ function implemented to look pretty .. er.

**Comment by KoichiYasuoka** [comment]
Thank you for merging my __repr__ for ConllEntry. I'm looking forward to next release.
