### ISSUE TITLE
link https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md mentioned under point 2 is not working

### ISSUE THREAD

**Issue by mithundeshmukh8** [adobe/NLP-Cube#96]
link https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md mentioned under Topic 2 - Train your model  is not working
Also please advice if in case there is .ipynb notebook for windows.
Thanks

**Comment by mithundeshmukh8** [comment]
on following part
 3. Advanced usage - Training a model on the UD Corpus.ipynb

**Comment by tiberiu44** [comment]
hi @mithundeshmukh8 

Thank you for noticing this. The resources were moved and we missed updating the Notebooks. I just corrected the link.

We don't have any Windows Notebook. From what I know, installing DyNET on windows with MKL support is not straight forward, but there are [tutorials](https://dynet.readthedocs.io/en/latest/install.html) on how to do that. The rest of the process should be the same.

Also, you could use Docker with a DyNET container and just add NLP-Cube on top of that. 

Hope this helps,
Tibi

**Comment by mithundeshmukh8** [comment]
Thanks
