### ISSUE TITLE
v1.1 models for 4 languages in performance table

### ISSUE THREAD

**Issue by futurulus** [adobe/NLP-Cube#98]
The metrics table in the README reports performance numbers for v1.1 models in most languages. I'm assuming that for languages that only have v1.0 results in the table, v1.1 models are not yet available. However, for four languages, v1.1 performance numbers are included in the table, but only v1.0 models are available in the online model repository:

* Ukrainian
* Urdu
* Vietnamese
* Chinese

Just double-checking that these models weren't left out unintentionally!

**Comment by dumitrescustefan** [comment]
Hi!

You're right, these models were missing from the online repo, we had some small issues but I reuploaded them right now. 

Thank you very much for your report. I'll close this issue, and if you have further problems with the 4 languages please re-open it.

Thanks again,
Stefan
